spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: DzgrFrgrm21HtqmUUgIv
            client-secret: bs7Z8Mw1Cy
            redirect-uri: "{baseUrl}/oauth/callback/{registrationId}" #"http://localhost:8080/redirect/oauth"  #
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
