
server:
  port: 8000

spring:
#  for h2
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/deumarketplace
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#  for mysql
  datasource:
    url: jdbc:mysql://localhost:3306/deuMarketplace?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: localDeuMarket
    password: 9999
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

# oauth include
  profiles:
    include: oauth

app:
  auth:
    tokenSecret: HrqO4UjEEvMUgDHyn4CFy6F8eY7ujJfj
#    accessTokenExpirationMsec: 600000 # 10min
    accessTokenExpirationMsec: 6000000 # 10min
#    refreshTokenExpirationMsec: 10800000 # 3H
    refreshTokenExpirationMsec: 10800000 # 3H
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect #

# log
logging.level:
  org.hibernate.SQL: debug

  org.springframework.security: debug
  # org.hibernate.type: trace