
server:
  port: 8000


spring:
#  for h2
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/deumarketplace
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#  for mysql
  datasource:
    url: jdbc:mysql://localhost:3306/deuMarketplace?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: localDeuMarket
    password: 9999
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        # show_sql: true
        format_sql: true

# oauth include
  profiles:
    include: oauth

  # file upload max size (파일 업로드 크기 설정)
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  auth:
    tokenSecret: HrqO4UjEEvMUgDHyn4CFy6F8eY7ujJfj
#    accessTokenExpirationMsec: 600000 # 10min
    accessTokenExpirationMsec: 6000000 # 10min
#    refreshTokenExpirationMsec: 10800000 # 3H
    refreshTokenExpirationMsec: 10800000 # 3H
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect #

# log
logging.level:
  org.hibernate.SQL: debug

  org.springframework.security: debug
  # org.hibernate.type: trace


# AWS Account Credentials (AWS 접근 키)
cloud:
  aws:
    credentials:
      accessKey: AKIA4IJIHFWPB3Z6EQLF
      secretKey: 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
  
# AWS S3 bucket Info (S3 버킷정보)
    s3:
      bucket: deumarket-img
    region:
      static: ap-northeast-2
    stack:
      auto: false
